### ISSUE TITLE
git checkout reference is not a tree

### ISSUE THREAD

**Issue by devbww** [googleapis/google-cloud-cpp#10784]
```
[12:11:30] [ID: 3243563] Executing command via SSH:
[12:11:30] 
[12:11:30] git -C /tmpfs/src/github/google-cloud-cpp checkout "de7a1715ee3936ae1ac3ecf3f0102469aa72ce79" --
[12:11:30] 
[12:11:31] fatal: reference is not a tree: de7a1715ee3936ae1ac3ecf3f0102469aa72ce79
[12:11:31] 
[12:11:31] 
[12:11:31] [ID: 3243563] Command finished after 0 secs, exit value: 128
[12:11:31] 
[12:11:31] 
[12:11:31][ERROR] Error executing task on agent
hudson.AbortException: Failed to run clone command: Command failed with exit code 1
	at com.google.devtools.kokoro.jenkins.plugin.github.CloneTask.runCloneCommand(CloneTask.java:173)
	at com.google.devtools.kokoro.jenkins.plugin.github.CloneTask.doInvoke(CloneTask.java:158)
	at com.google.devtools.kokoro.jenkins.plugin.github.CloneTask.doInvoke(CloneTask.java:37)
	at com.google.devtools.kokoro.jenkins.shared.BaseMasterToAgentFileCallable.invoke(BaseMasterToAgentFileCallable.java:83)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2731)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:336)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at com.google.devtools.kokoro.remoting.RpcEngine$1$1.run(RpcEngine.java:99)
	at java.base/java.lang.Thread.run(Unknown Source)

[12:11:36][ERROR] Failed to run clone command: Command failed with exit code 1
```
and yet
```
% git rev-parse --verify de7a1715ee3936ae1ac3ecf3f0102469aa72ce79 && echo OK
de7a1715ee3936ae1ac3ecf3f0102469aa72ce79
OK
```

* http://sponge2.corp.google.com/1637738e-e53a-4b95-b0de-9b4421a28dd0
* http://sponge2.corp.google.com/da4829e5-b489-4a39-93f3-2c9c94bea9ed

**Comment by devbww** [comment]
It looks like the real problem is a few lines up, where `git clone` claims to have succeeded, but after 600 seconds, which smells like a network timeout.
```
[10:11:28] [ID: 8639268] Executing command via SSH:
[10:11:28] 
[10:11:28] git clone https://github.com/googleapis/google-cloud-cpp.git T:/src/github/google-cloud-cpp
[10:11:28] 
[10:11:29] Cloning into '/tmpfs/src/github/google-cloud-cpp'...
[10:21:29] 
[10:21:29] 
[10:21:29] [ID: 8639268] Command finished after 600 secs, exit value: 0
```
- http://sponge2.corp.google.com/8be03fad-e47a-49e3-bb33-3606e8613126

**Comment by coryan** [comment]
No repeats in 90d, closing.
