### ISSUE TITLE
publish-docs docuploader TimeoutError: The read operation timed out

### ISSUE THREAD

**Issue by devbww** [googleapis/google-cloud-cpp#12916]
https://console.cloud.google.com/cloud-build/builds;region=us-east1/1e56ab7f-7b3d-4acc-a210-dac7f235f2f9?project=cloud-cpp-testing-resources&e=-13802955&mods=logs_tg_prod

```
Step #3: [35mdocuploader > [32mCool, I have those tarred up.[0m
Step #3: [35mdocuploader > [34mOkay, I'm sending them to the cloudâ„¢ now.[0m
Step #3: Traceback (most recent call last):
Step #3:   File "/h/.venv/docuploader/lib64/python3.11/site-packages/urllib3/connectionpool.py", line 466, in _make_request
Step #3:     six.raise_from(e, None)
Step #3:   File "<string>", line 3, in raise_from
Step #3:   File "/h/.venv/docuploader/lib64/python3.11/site-packages/urllib3/connectionpool.py", line 461, in _make_request
Step #3:     httplib_response = conn.getresponse()
Step #3:                        ^^^^^^^^^^^^^^^^^^
Step #3:   File "/usr/lib64/python3.11/http/client.py", line 1378, in getresponse
Step #3:     response.begin()
Step #3:   File "/usr/lib64/python3.11/http/client.py", line 318, in begin
Step #3:     version, status, reason = self._read_status()
Step #3:                               ^^^^^^^^^^^^^^^^^^^
Step #3:   File "/usr/lib64/python3.11/http/client.py", line 279, in _read_status
Step #3:     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
Step #3:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Step #3:   File "/usr/lib64/python3.11/socket.py", line 706, in readinto
Step #3:     return self._sock.recv_into(b)
Step #3:            ^^^^^^^^^^^^^^^^^^^^^^^
Step #3:   File "/usr/lib64/python3.11/ssl.py", line 1311, in recv_into
Step #3:     return self.read(nbytes, buffer)
Step #3:            ^^^^^^^^^^^^^^^^^^^^^^^^^
Step #3:   File "/usr/lib64/python3.11/ssl.py", line 1167, in read
Step #3:     return self._sslobj.read(len, buffer)
Step #3:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Step #3: TimeoutError: The read operation timed out
```

**Comment by dbolduc** [comment]
@coryan took us off `docuploader`. The bug is irrelevant now.
