### ISSUE TITLE
storage_internal_storage_stub_factory_test segfault

### ISSUE THREAD

**Issue by alevenberg** [googleapis/google-cloud-cpp#13084]
```
The following tests FAILED:
    324 - storage_internal_storage_stub_factory_test (SEGFAULT)
Errors while running CTest
==> 🕑 cmake-oldest-deps completed in 472.592 seconds
```

```
319/535 Test #324: storage_internal_storage_stub_factory_test ................................***Exception: SegFault  0.08 sec
Running main() from gmock_main.cc
Note: Randomizing tests' orders with a seed of 98196 .
[==========] Running 6 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 6 tests from StorageStubFactory
[ RUN      ] StorageStubFactory.StartResumableWrite
[       OK ] StorageStubFactory.StartResumableWrite (26 ms)
[ RUN      ] StorageStubFactory.WriteObject
[       OK ] StorageStubFactory.WriteObject (4 ms)
[ RUN      ] StorageStubFactory.ReadObject
```

Build FAILURE: cmake-oldest-deps-ci https://console.cloud.google.com/cloud-build/builds;region=us-east1/1aebc546-950a-4c7c-bb08-06c328e9efaa?project=936212892354

**Comment by coryan** [comment]
Just finished 1,000 runs locally, using the `cmake-oldest-pr` build.  No repro.

Also ran with valgrind on my workstation, no repro.

**Comment by coryan** [comment]
100 runs with valgrind, no repro.

**Comment by alevenberg** [comment]
Appeared again on https://github.com/googleapis/google-cloud-cpp/pull/13085/checks?check_run_id=18527603014

**Comment by alevenberg** [comment]
Seems like it was just enabled on this check https://github.com/googleapis/google-cloud-cpp/commit/4b9e02422f9538db32909b6035eb345b68a94e0f

**Comment by coryan** [comment]
No repro with:

```sh
ci/cloudbuild/build.sh -t cmake-oldest-deps-pr --docker-shell
ci/cloudbuild/build.sh --local --build cmake-oldest-deps
env -C cmake-out/build/ GTEST_SHUFFLE=1 ctest -Q -R storage_internal_storage_stub_factory_test --repeat-until-fail 10000 -j 100
```

**Comment by alevenberg** [comment]
For the record it is at 
```
Step #3: 309/535 Test #324: storage_internal_storage_stub_factory_test ................................***Exception: SegFault  0.07 sec
Step #3: Running main() from gmock_main.cc
Step #3: Note: Randomizing tests' orders with a seed of 52119 .
Step #3: [==========] Running 6 tests from 1 test suite.
Step #3: [----------] Global test environment set-up.
Step #3: [----------] 6 tests from StorageStubFactory
Step #3: [ RUN      ] StorageStubFactory.WriteObject
Step #3: [       OK ] StorageStubFactory.WriteObject (26 ms)
Step #3: [ RUN      ] StorageStubFactory.TracingDisabled
```

**Comment by coryan** [comment]
```
valgrind cmake-out/build/google/cloud/storage/internal_storage_stub_factory_test --gtest_shuffle --gtest_repeat=100
```

No repro either.

**Comment by coryan** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/8c312f5a-bc93-48f5-a045-3f61318915c7;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/b760eafe4f02317e9bb53fa492e034546dff8726/ubuntu-focal-cmake-oldest-deps/log-8c312f5a-bc93-48f5-a045-3f61318915c7.txt

**Comment by devbww** [comment]
I'm not sure how useful it is, but I managed to catch a SEGV with this backtrace:
```
#0  0x0000000000c6e4b0 in std::_Rb_tree<grpc_core::ConnectivityStateWatcherInterface*, std::pair<grpc_core::ConnectivityStateWatcherInterface* const, std::unique_ptr<grpc_core::ConnectivityStateWatcherInterface, grpc_core::OrphanableDelete> >, std::_Select1st<std::pair<grpc_core::ConnectivityStateWatcherInterface* const, std::unique_ptr<grpc_core::ConnectivityStateWatcherInterface, grpc_core::OrphanableDelete> > >, std::less<grpc_core::ConnectivityStateWatcherInterface*>, std::allocator<std::pair<grpc_core::ConnectivityStateWatcherInterface* const, std::unique_ptr<grpc_core::ConnectivityStateWatcherInterface, grpc_core::OrphanableDelete> > > >::equal_range (this=0x11e7c51, __k=@0x7f560f7fd310: 0x2ff0210)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_tree.h:2002
#1  0x0000000000c6e3f4 in std::_Rb_tree<grpc_core::ConnectivityStateWatcherInterface*, std::pair<grpc_core::ConnectivityStateWatcherInterface* const, std::unique_ptr<grpc_core::ConnectivityStateWatcherInterface, grpc_core::OrphanableDelete> >, std::_Select1st<std::pair<grpc_core::ConnectivityStateWatcherInterface* const, std::unique_ptr<grpc_core::ConnectivityStateWatcherInterface, grpc_core::OrphanableDelete> > >, std::less<grpc_core::ConnectivityStateWatcherInterface*>, std::allocator<std::pair<grpc_core::ConnectivityStateWatcherInterface* const, std::unique_ptr<grpc_core::ConnectivityStateWatcherInterface, grpc_core::OrphanableDelete> > > >::erase
    (this=0x11e7c51, __x=@0x7f560f7fd310: 0x2ff0210)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_tree.h:2539
#2  0x0000000000c6cf2d in std::map<grpc_core::ConnectivityStateWatcherInterface*, std::unique_ptr<grpc_core::ConnectivityStateWatcherInterface, grpc_core::OrphanableDelete>, std::less<grpc_core::ConnectivityStateWatcherInterface*>, std::allocator<std::pair<grpc_core::ConnectivityStateWatcherInterface* const, std::unique_ptr<grpc_core::ConnectivityStateWatcherInterface, grpc_core::OrphanableDelete> > > >::erase (this=0x11e7c51, __x=@0x7f560f7fd310: 0x2ff0210)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_map.h:1068
#3  0x0000000000c6c646 in grpc_core::ConnectivityStateTracker::RemoveWatcher (this=0x11e7c39, watcher=0x2ff0210)
    at /h/vcpkg-2023.10.19/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/lib/transport/connectivity_state.cc:147
#4  0x0000000000b69fc6 in grpc_core::(anonymous namespace)::ChannelData::ExternalConnectivityWatcher::RemoveWatcherLocked (
    this=0x2ff0210)
    at /h/vcpkg-2023.10.19/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/ext/filters/client_channel/client_channel.cc:1656
#5  0x0000000000b6bae8 in grpc_core::(anonymous namespace)::ChannelData::ExternalConnectivityWatcher::Notify(grpc_connectivity_state, absl::lts_2020_09_23::Status const&)::$_1::operator()() const (this=0x2edc078)
    at /h/vcpkg-2023.10.19/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/ext/filters/client_channel/client_channel.cc:1631
#6  0x0000000000b6b9ad in std::_Function_handler<void (), grpc_core::(anonymous namespace)::ChannelData::ExternalConnectivityWatcher::Notify(grpc_connectivity_state, absl::lts_2020_09_23::Status const&)::$_1>::_M_invoke(std::_Any_data const&) (__functor=...)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:300
#7  0x00000000004a03ee in std::function<void ()>::operator()() const (this=0x2edc078)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:688
#8  0x0000000000c001b1 in grpc_core::WorkSerializer::WorkSerializerImpl::DrainQueue (this=0x2fe1f70)
    at /h/vcpkg-2023.10.19/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/lib/iomgr/work_serializer.cc:138
#9  0x0000000000bffe57 in grpc_core::WorkSerializer::WorkSerializerImpl::Run(std::function<void ()>, grpc_core::DebugLocation const&) (this=0x2fe1f70, callback=..., location=...)
    at /h/vcpkg-2023.10.19/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/lib/iomgr/work_serializer.cc:69
#10 0x0000000000c0035e in grpc_core::WorkSerializer::Run(std::function<void ()>, grpc_core::DebugLocation const&) (this=0x3018c40,
    callback=..., location=...)
    at /h/vcpkg-2023.10.19/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/lib/iomgr/work_serializer.cc:152
#11 0x0000000000b5b276 in grpc_core::(anonymous namespace)::ChannelData::SubchannelWrapper::WatcherWrapper::OnConnectivityStateChange (this=0x7f55fc0020e0)
    at /h/vcpkg-2023.10.19/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/ext/filters/client_channel/client_channel.cc:1442
#12 0x0000000000bb49ce in grpc_core::Subchannel::AsyncWatcherNotifierLocked::AsyncWatcherNotifierLocked(grpc_core::RefCountedPtr<grpc_core::Subchannel::ConnectivityStateWatcherInterface>, grpc_core::Subchannel*, grpc_connectivity_state, absl::lts_2020_09_23::Status const&)::{lambda(void*, grpc_error*)#1}::operator()(void*, grpc_error*) const (this=0x7f55fc003fd0, arg=0x7f55fc003fd0)
    at /h/vcpkg-2023.10.19/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/ext/filters/client_channel/subchannel.cc:379
#13 0x0000000000bb498d in grpc_core::Subchannel::AsyncWatcherNotifierLocked::AsyncWatcherNotifierLocked(grpc_core::RefCountedPtr<grpc_core::Subchannel::ConnectivityStateWatcherInterface>, grpc_core::Subchannel*, grpc_connectivity_state, absl::lts_2020_09_23::Status const&)::{lambda(void*, grpc_error*)#1}::__invoke(void*, grpc_error*) (arg=0x7f55fc003fd0)
    at /h/vcpkg-2023.10.19/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/ext/filters/client_channel/subchannel.cc:379
#14 0x0000000000be454e in exec_ctx_run (closure=0x7f55fc003fd8, error=0x0)
    at /h/vcpkg-2023.10.19/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/lib/iomgr/exec_ctx.cc:40
#15 0x0000000000be43ea in grpc_core::ExecCtx::Flush (this=0x7f560f7fd900)
    at /h/vcpkg-2023.10.19/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/lib/iomgr/exec_ctx.cc:157
#16 0x0000000000e55821 in pollset_work (pollset=0x2edbc18, worker_hdl=0x0, deadline=52)
    at /h/vcpkg-2023.10.19/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/lib/iomgr/ev_epollex_linux.cc:1145
#17 0x0000000000e0afb3 in pollset_work (pollset=0x2edbc18, worker=0x0, deadline=52)
    at /h/vcpkg-2023.10.19/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/lib/iomgr/ev_posix.cc:323
#18 0x0000000000be8c60 in grpc_pollset_work (pollset=0x2edbc18, worker=0x0, deadline=52)
    at /h/vcpkg-2023.10.19/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/lib/iomgr/pollset.cc:48
#19 0x0000000000c511b6 in cq_next (cq=0x2edbb10, deadline=..., reserved=0x0)
    at /h/vcpkg-2023.10.19/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/lib/surface/completion_queue.cc:1059
#20 0x0000000000c5056c in grpc_completion_queue_next (cq=0x2edbb10, deadline=..., reserved=0x0)
    at /h/vcpkg-2023.10.19/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/lib/surface/completion_queue.cc:1135
#21 0x0000000000945443 in grpc::CompletionQueue::AsyncNextInternal (this=0x2edc9d0, tag=0x7f560f7fdbc0, ok=0x7f560f7fdbbf,
    deadline=...) at /h/vcpkg-2023.10.19/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/cpp/common/completion_queue_cc.cc:54
#22 0x0000000000752cca in grpc::CompletionQueue::NextStatus grpc::CompletionQueue::AsyncNext<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > > >(void**, bool*, std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > > const&) ()
#23 0x000000000074f37e in google::cloud::v2_19::internal::DefaultCompletionQueueImpl::Run() ()
#24 0x000000000072db01 in google::cloud::v2_19::CompletionQueue::Run() ()
#25 0x000000000072c016 in google::cloud::v2_19::internal::AutomaticallyCreatedBackgroundThreads::AutomaticallyCreatedBackgroundThreads(unsigned long)::$_0::operator()() const::{lambda(google::cloud::v2_19::CompletionQueue, google::cloud::v2_19::promise<void>&)#1}::operator()(google::cloud::v2_19::CompletionQueue, google::cloud::v2_19::promise<void>&) const ()
#26 0x000000000072bfbe in void std::__invoke_impl<void, google::cloud::v2_19::internal::AutomaticallyCreatedBackgroundThreads::AutomaticallyCreatedBackgroundThreads(unsigned long)::$_0::operator()() const::{lambda(google::cloud::v2_19::CompletionQueue, google::cloud::v2_19::promise<void>&)#1}, google::cloud::v2_19::CompletionQueue, std::reference_wrapper<google::cloud::v2_19::promise<void> > >(std::__invoke_other, google::cloud::v2_19::internal::AutomaticallyCreatedBackgroundThreads::AutomaticallyCreatedBackgroundThreads(unsigned long)::$_0::operator()() const::{lambda(google::cloud::v2_19::CompletionQueue, google::cloud::v2_19::promise<void>&)#1}&&, google::cloud::v2_19::CompletionQueue&&, std::reference_wrapper<google::cloud::v2_19::promise<void> >&&) ()
#27 0x000000000072beb7 in std::__invoke_result<google::cloud::v2_19::internal::AutomaticallyCreatedBackgroundThreads::AutomaticallyCreatedBackgroundThreads(unsigned long)::$_0::operator()() const::{lambda(google::cloud::v2_19::CompletionQueue, google::cloud::v2_19::promise<void>&)#1}, google::cloud::v2_19::CompletionQueue, std::reference_wrapper<google::cloud::v2_19::promise<void> > >::type std::__invoke<google::cloud::v2_19::internal::AutomaticallyCreatedBackgroundThreads::AutomaticallyCreatedBackgroundThreads(unsigned long)::$_0::operator()() const::{lambda(google::cloud::v2_19::CompletionQueue, google::cloud::v2_19::promise<void>&)#1}, google::cloud::v2_19::CompletionQueue, std::reference_wrapper<google::cloud::v2_19::promise<void> > >(google::cloud::v2_19::internal::AutomaticallyCreatedBackgroundThreads::AutomaticallyCreatedBackgroundThreads(unsigned long)::$_0::operator()() const::{lambda(google::cloud::v2_19::CompletionQueue, google::cloud::v2_19::promise<void>&)#1}&&, google::cloud::v2_19::CompletionQueue&&, std::reference_wrapper<google::cloud::v2_19::promise<void> >&&) ()
#28 0x000000000072be5e in void std::thread::_Invoker<std::tuple<google::cloud::v2_19::internal::AutomaticallyCreatedBackgroundThreads::AutomaticallyCreatedBackgroundThreads(unsigned long)::$_0::operator()() const::{lambda(google::cloud::v2_19::CompletionQueue, google::cloud::v2_19::promise<void>&)#1}, google::cloud::v2_19::CompletionQueue, std::reference_wrapper<google::cloud::v2_19::promise<void> > > >::_M_invoke<0ul, 1ul, 2ul>(std::_Index_tuple<0ul, 1ul, 2ul>) ()
#29 0x000000000072bdf5 in std::thread::_Invoker<std::tuple<google::cloud::v2_19::internal::AutomaticallyCreatedBackgroundThreads::AutomaticallyCreatedBackgroundThreads(unsigned long)::$_0::operator()() const::{lambda(google::cloud::v2_19::CompletionQueue, google::cloud::v2_19::promise<void>&)#1}, google::cloud::v2_19::CompletionQueue, std::reference_wrapper<google::cloud::v2_19::promise<void> > > >::operator()() ()
#30 0x000000000072bcbe in std::thread::_State_impl<std::thread::_Invoker<std::tuple<google::cloud::v2_19::internal::AutomaticallyCreatedBackgroundThreads::AutomaticallyCreatedBackgroundThreads(unsigned long)::$_0::operator()() const::{lambda(google::cloud::v2_19::CompletionQueue, google::cloud::v2_19::promise<void>&)#1}, google::cloud::v2_19::CompletionQueue, std::reference_wrapper<google::cloud::v2_19::promise<void> > > > >::_M_run() ()
#31 0x00007f5615513df4 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::swap(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#32 0x00007ffd91ef7f2e in ?? ()
#33 0x00007f561562d609 in ?? ()
#34 0x0000000000000000 in ?? ()
```
