### ISSUE TITLE
Segfault in `storage_internal_grpc_stub_failures_test` under `cmake-oldest-deps`

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#13114]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/f1b18797-333c-439d-aafa-2236940f924e;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/40e48b88447dfe93395c0953761eb4c2997aca5e/ubuntu-focal-cmake-oldest-deps/log-f1b18797-333c-439d-aafa-2236940f924e.txt

I suspect this is similar to #13084

**Comment by coryan** [comment]
Running this about 10,000 times under `ci/cloudbuild/build.sh -t cmake-oldest-deps-pr --docker-shell`:

The crash seems to be in:

```
#0  0x0000000000f5a340 in std::_Rb_tree<grpc_core::ConnectivityStateWatcherInterface*, std::pair<grpc_core::ConnectivityStateWatcherInterface* const, std::unique_ptr<grpc_core::ConnectivityStateWatcherInterface, grpc_core::OrphanableDelete> >, std::_Select1st<std::pair<grpc_core::ConnectivityStateWatcherInterface* const, std::unique_ptr<grpc_core::ConnectivityStateWatcherInterface, grpc_core::OrphanableDelete> > >, std::less<grpc_core::ConnectivityStateWatcherInterface*>, std::allocator<std::pair<grpc_core::ConnectivityStateWatcherInterface* const, std::unique_ptr<grpc_core::ConnectivityStateWatcherInterface, grpc_core::OrphanableDelete> > > >::equal_range (this=0x152be69, __k=@0x7f750d31c870: 0x7f74fc04f990) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_tree.h:2002
#1  0x0000000000f5a284 in std::_Rb_tree<grpc_core::ConnectivityStateWatcherInterface*, std::pair<grpc_core::ConnectivityStateWatcherInterface* const, std::unique_ptr<grpc_core::ConnectivityStateWatcherInterface, grpc_core::OrphanableDelete> >, std::_Select1st<std::pair<grpc_core::ConnectivityStateWatcherInterface* const, std::unique_ptr<grpc_core::ConnectivityStateWatcherInterface, grpc_core::OrphanableDelete> > >, std::less<grpc_core::ConnectivityStateWatcherInterface*>, std::allocator<std::pair<grpc_core::ConnectivityStateWatcherInterface* const, std::unique_ptr<grpc_core::ConnectivityStateWatcherInterface, grpc_core::OrphanableDelete> > > >::erase (this=0x152be69, __x=@0x7f750d31c870: 0x7f74fc04f990) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_tree.h:2539
#2  0x0000000000f58dbd in std::map<grpc_core::ConnectivityStateWatcherInterface*, std::unique_ptr<grpc_core::ConnectivityStateWatcherInterface, grpc_core::OrphanableDelete>, std::less<grpc_core::ConnectivityStateWatcherInterface*>, std::allocator<std::pair<grpc_core::ConnectivityStateWatcherInterface* const, std::unique_ptr<grpc_core::ConnectivityStateWatcherInterface, grpc_core::OrphanableDelete> > > >::erase (this=0x152be69, __x=@0x7f750d31c870: 0x7f74fc04f990) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_map.h:1068
#3  0x0000000000f584d6 in grpc_core::ConnectivityStateTracker::RemoveWatcher (this=0x152be51, watcher=0x7f74fc04f990) at /h/vcpkg-2023.12.12/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/lib/transport/connectivity_state.cc:147
#4  0x0000000000e5d056 in grpc_core::(anonymous namespace)::ChannelData::ExternalConnectivityWatcher::RemoveWatcherLocked (this=0x7f74fc04f990) at /h/vcpkg-2023.12.12/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/ext/filters/client_channel/client_channel.cc:1656
#5  0x0000000000e5eb78 in grpc_core::(anonymous namespace)::ChannelData::ExternalConnectivityWatcher::Notify(grpc_connectivity_state, absl::lts_2020_09_23::Status const&)::$_1::operator()() const (this=0x7f74fc007eb8)
    at /h/vcpkg-2023.12.12/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/ext/filters/client_channel/client_channel.cc:1631
#6  0x0000000000e5ea3d in std::_Function_handler<void (), grpc_core::(anonymous namespace)::ChannelData::ExternalConnectivityWatcher::Notify(grpc_connectivity_state, absl::lts_2020_09_23::Status const&)::$_1>::_M_invoke(std::_Any_data const&) (__functor=...)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:300
#7  0x000000000050bbfe in std::function<void ()>::operator()() const (this=0x7f74fc007eb8) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:688
#8  0x0000000000eed6a1 in grpc_core::WorkSerializer::WorkSerializerImpl::DrainQueue (this=0x377c3f0) at /h/vcpkg-2023.12.12/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/lib/iomgr/work_serializer.cc:138
#9  0x0000000000eed347 in grpc_core::WorkSerializer::WorkSerializerImpl::Run(std::function<void ()>, grpc_core::DebugLocation const&) (this=0x377c3f0, callback=..., location=...)
    at /h/vcpkg-2023.12.12/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/lib/iomgr/work_serializer.cc:69
#10 0x0000000000eed84e in grpc_core::WorkSerializer::Run(std::function<void ()>, grpc_core::DebugLocation const&) (this=0x377c3e0, callback=..., location=...) at /h/vcpkg-2023.12.12/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/lib/iomgr/work_serializer.cc:152
#11 0x0000000000e4e306 in grpc_core::(anonymous namespace)::ChannelData::SubchannelWrapper::WatcherWrapper::OnConnectivityStateChange (this=0x3935c00) at /h/vcpkg-2023.12.12/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/ext/filters/client_channel/client_channel.cc:1442
#12 0x0000000000ea713e in grpc_core::Subchannel::AsyncWatcherNotifierLocked::AsyncWatcherNotifierLocked(grpc_core::RefCountedPtr<grpc_core::Subchannel::ConnectivityStateWatcherInterface>, grpc_core::Subchannel*, grpc_connectivity_state, absl::lts_2020_09_23::Status const&)::{lambda(void*, grpc_error*)#1}::operator()(void*, grpc_error*) const (this=0x7f74fc031490, arg=0x7f74fc031490) at /h/vcpkg-2023.12.12/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/ext/filters/client_channel/subchannel.cc:379
#13 0x0000000000ea70fd in grpc_core::Subchannel::AsyncWatcherNotifierLocked::AsyncWatcherNotifierLocked(grpc_core::RefCountedPtr<grpc_core::Subchannel::ConnectivityStateWatcherInterface>, grpc_core::Subchannel*, grpc_connectivity_state, absl::lts_2020_09_23::Status const&)::{lambda(void*, grpc_error*)#1}::__invoke(void*, grpc_error*) (arg=0x7f74fc031490) at /h/vcpkg-2023.12.12/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/ext/filters/client_channel/subchannel.cc:379
#14 0x0000000000ed1b1e in exec_ctx_run (closure=0x7f74fc031498, error=0x0) at /h/vcpkg-2023.12.12/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/lib/iomgr/exec_ctx.cc:40
#15 0x0000000000ed19ba in grpc_core::ExecCtx::Flush (this=0x7f750d31cca0) at /h/vcpkg-2023.12.12/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/lib/iomgr/exec_ctx.cc:157
#16 0x0000000000eec93e in run_some_timers () at /h/vcpkg-2023.12.12/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/lib/iomgr/timer_manager.cc:134
#17 0x0000000000eec6a5 in timer_main_loop () at /h/vcpkg-2023.12.12/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/lib/iomgr/timer_manager.cc:237
#18 0x0000000000eec5ff in timer_thread (completed_thread_ptr=0x7f74f8001180) at /h/vcpkg-2023.12.12/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/lib/iomgr/timer_manager.cc:284
#19 0x0000000001238256 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::{lambda(void*)#1}::operator()(void*) const (this=0x7f74f80011e0, v=0x7f74f80011e0)
    at /h/vcpkg-2023.12.12/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/lib/gprpp/thd_posix.cc:140
#20 0x0000000001238115 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::{lambda(void*)#1}::__invoke(void*) (v=0x7f74f80011e0)
    at /h/vcpkg-2023.12.12/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/lib/gprpp/thd_posix.cc:110
#21 0x00007f750f14f609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#22 0x00007f750ee6f353 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

The main thread is blocked waiting for background threads:

```
#0  __pthread_clockjoin_ex (threadid=140140718778112, thread_return=0x0, clockid=<optimized out>, abstime=<optimized out>, block=<optimized out>) at pthread_join_common.c:145
#1  0x00007f750f036057 in std::thread::join() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x0000000000a3b581 in google::cloud::v2_20::internal::AutomaticallyCreatedBackgroundThreads::Shutdown() () at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_deque.h:94
#3  0x0000000000a3b483 in google::cloud::v2_20::internal::AutomaticallyCreatedBackgroundThreads::~AutomaticallyCreatedBackgroundThreads() () at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_deque.h:94
#4  0x0000000000a3b73c in google::cloud::v2_20::internal::AutomaticallyCreatedBackgroundThreads::~AutomaticallyCreatedBackgroundThreads() () at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_deque.h:94
#5  0x000000000050f21f in std::default_delete<google::cloud::v2_20::BackgroundThreads>::operator()(google::cloud::v2_20::BackgroundThreads*) const ()
#6  0x00000000004e925d in std::unique_ptr<google::cloud::v2_20::BackgroundThreads, std::default_delete<google::cloud::v2_20::BackgroundThreads> >::~unique_ptr() ()
#7  0x00000000004f647e in google::cloud::storage_internal::v2_20::GrpcStub::~GrpcStub() ()
#8  0x00000000004f64cc in google::cloud::storage_internal::v2_20::GrpcStub::~GrpcStub() ()
#9  0x00000000004c921f in std::default_delete<google::cloud::storage_internal::v2_20::GenericStub>::operator()(google::cloud::storage_internal::v2_20::GenericStub*) const ()
#10 0x00000000004c6ffd in std::unique_ptr<google::cloud::storage_internal::v2_20::GenericStub, std::default_delete<google::cloud::storage_internal::v2_20::GenericStub> >::~unique_ptr() ()
#11 0x00000000007cfcfc in google::cloud::storage::v2_20::internal::StorageConnectionImpl::~StorageConnectionImpl() ()
#12 0x00000000007cfd3c in google::cloud::storage::v2_20::internal::StorageConnectionImpl::~StorageConnectionImpl() ()
#13 0x00000000007d0f5f in std::_Sp_counted_ptr<google::cloud::storage::v2_20::internal::StorageConnectionImpl*, (__gnu_cxx::_Lock_policy)2>::_M_dispose() ()
#14 0x000000000043be8c in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x36b7d60) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/shared_ptr_base.h:155
#15 0x000000000043be3a in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x3b3ad88) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/shared_ptr_base.h:730
#16 0x0000000000449c5e in std::__shared_ptr<google::cloud::storage::v2_20::internal::StorageConnection, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() ()
#17 0x0000000000449c38 in std::shared_ptr<google::cloud::storage::v2_20::internal::StorageConnection>::~shared_ptr() ()
#18 0x0000000000449c15 in google::cloud::storage::v2_20::Client::~Client() ()
#19 0x0000000000424896 in google::cloud::storage::v2_20::internal::(anonymous namespace)::GrpcClientFailuresTest::~GrpcClientFailuresTest() ()
#20 0x0000000000437498 in google::cloud::storage::v2_20::internal::(anonymous namespace)::GrpcClientFailuresTest_SignBlob_Test::~GrpcClientFailuresTest_SignBlob_Test() ()
#21 0x00000000004374bc in google::cloud::storage::v2_20::internal::(anonymous namespace)::GrpcClientFailuresTest_SignBlob_Test::~GrpcClientFailuresTest_SignBlob_Test() ()
#22 0x00000000008fd6fb in testing::Test::DeleteSelf_ (this=0x3b3ac90) at /h/vcpkg-2023.12.12/buildtrees/gtest/src/ase-1.12.0-dae7aa2018.clean/googletest/include/gtest/gtest.h:318
#23 0x0000000000914b94 in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void> (object=0x3b3ac90, method=(void (testing::Test::*)(class testing::Test * const)) 0x8fd6d0 <testing::Test::DeleteSelf_()>, location=0x14c206a "the test fixture's destructor")
    at /h/vcpkg-2023.12.12/buildtrees/gtest/src/ase-1.12.0-dae7aa2018.clean/googletest/src/gtest.cc:2599
#24 0x00000000008fce4b in testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void> (object=0x3b3ac90, method=(void (testing::Test::*)(class testing::Test * const)) 0x8fd6d0 <testing::Test::DeleteSelf_()>, location=0x14c206a "the test fixture's destructor")
    at /h/vcpkg-2023.12.12/buildtrees/gtest/src/ase-1.12.0-dae7aa2018.clean/googletest/src/gtest.cc:2635
#25 0x00000000008df6ee in testing::TestInfo::Run (this=0x365dc10) at /h/vcpkg-2023.12.12/buildtrees/gtest/src/ase-1.12.0-dae7aa2018.clean/googletest/src/gtest.cc:2859
#26 0x00000000008dff6e in testing::TestSuite::Run (this=0x365b710) at /h/vcpkg-2023.12.12/buildtrees/gtest/src/ase-1.12.0-dae7aa2018.clean/googletest/src/gtest.cc:3012
#27 0x00000000008f07b1 in testing::internal::UnitTestImpl::RunAllTests (this=0x3685af0) at /h/vcpkg-2023.12.12/buildtrees/gtest/src/ase-1.12.0-dae7aa2018.clean/googletest/src/gtest.cc:5870
#28 0x0000000000917824 in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0x3685af0, 
    method=(bool (testing::internal::UnitTestImpl::*)(class testing::internal::UnitTestImpl * const)) 0x8f0340 <testing::internal::UnitTestImpl::RunAllTests()>, location=0x14c276d "auxiliary test code (environments or event listeners)")
    at /h/vcpkg-2023.12.12/buildtrees/gtest/src/ase-1.12.0-dae7aa2018.clean/googletest/src/gtest.cc:2599
#29 0x00000000008ff2bb in testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0x3685af0, 
    method=(bool (testing::internal::UnitTestImpl::*)(class testing::internal::UnitTestImpl * const)) 0x8f0340 <testing::internal::UnitTestImpl::RunAllTests()>, location=0x14c276d "auxiliary test code (environments or event listeners)")
    at /h/vcpkg-2023.12.12/buildtrees/gtest/src/ase-1.12.0-dae7aa2018.clean/googletest/src/gtest.cc:2635
#30 0x00000000008f02f6 in testing::UnitTest::Run (this=0x1c6c808 <testing::UnitTest::GetInstance()::instance>) at /h/vcpkg-2023.12.12/buildtrees/gtest/src/ase-1.12.0-dae7aa2018.clean/googletest/src/gtest.cc:5444
#31 0x00000000008b5561 in RUN_ALL_TESTS () at /h/vcpkg-2023.12.12/buildtrees/gtest/src/ase-1.12.0-dae7aa2018.clean/googletest/include/gtest/gtest.h:2293
#32 0x00000000008b5542 in main (argc=1, argv=0x7fffe9913e58) at /h/vcpkg-2023.12.12/buildtrees/gtest/src/ase-1.12.0-dae7aa2018.clean/googlemock/src/gmock_main.cc:70
```

Other threads are blocked too:

```
(gdb) thread 7
[Switching to thread 7 (Thread 0x7f750caf7700 (LWP 3159380))]
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
38      in ../sysdeps/unix/sysv/linux/x86_64/syscall.S
(gdb) bt
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x0000000001282d96 in absl::lts_2020_09_23::synchronization_internal::Futex::WaitUntil (v=0x7f750ed3e650, val=0, t=...) at /h/vcpkg-2023.12.12/buildtrees/abseil/src/df0e5d068c-e45371f367.clean/absl/synchronization/internal/waiter.cc:115
#2  0x0000000001282931 in absl::lts_2020_09_23::synchronization_internal::Waiter::Wait (this=0x7f750ed3e650, t=...) at /h/vcpkg-2023.12.12/buildtrees/abseil/src/df0e5d068c-e45371f367.clean/absl/synchronization/internal/waiter.cc:159
#3  0x00000000012820ca in AbslInternalPerThreadSemWait (t=...) at /h/vcpkg-2023.12.12/buildtrees/abseil/src/df0e5d068c-e45371f367.clean/absl/synchronization/internal/per_thread_sem.cc:93
#4  0x000000000127f28d in absl::lts_2020_09_23::synchronization_internal::PerThreadSem::Wait (t=...) at /h/vcpkg-2023.12.12/buildtrees/abseil/src/df0e5d068c-e45371f367.clean/absl/synchronization/internal/per_thread_sem.h:112
#5  0x000000000127ebd3 in absl::lts_2020_09_23::Mutex::DecrementSynchSem (mu=0x1c72468 <g_mu>, w=0x7f750ed3e600, t=...) at /h/vcpkg-2023.12.12/buildtrees/abseil/src/df0e5d068c-e45371f367.clean/absl/synchronization/mutex.cc:568
#6  0x000000000127a431 in absl::lts_2020_09_23::CondVar::WaitCommon (this=0x1c72470 <g_cv_wait>, mutex=0x1c72468 <g_mu>, t=...) at /h/vcpkg-2023.12.12/buildtrees/abseil/src/df0e5d068c-e45371f367.clean/absl/synchronization/mutex.cc:2547
#7  0x000000000127a66a in absl::lts_2020_09_23::CondVar::Wait (this=0x1c72470 <g_cv_wait>, mu=0x1c72468 <g_mu>) at /h/vcpkg-2023.12.12/buildtrees/abseil/src/df0e5d068c-e45371f367.clean/absl/synchronization/mutex.cc:2582
#8  0x00000000012334d1 in gpr_cv_wait (cv=0x1c72470 <g_cv_wait>, mu=0x1c72468 <g_mu>, abs_deadline=...) at /h/vcpkg-2023.12.12/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/lib/gpr/sync_abseil.cc:85
#9  0x0000000000eecb42 in wait_until (next=9223372036854775807) at /h/vcpkg-2023.12.12/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/lib/iomgr/timer_manager.cc:200
#10 0x0000000000eec6f9 in timer_main_loop () at /h/vcpkg-2023.12.12/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/lib/iomgr/timer_manager.cc:255
#11 0x0000000000eec5ff in timer_thread (completed_thread_ptr=0x3a29e60) at /h/vcpkg-2023.12.12/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/lib/iomgr/timer_manager.cc:284
#12 0x0000000001238256 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::{lambda(void*)#1}::operator()(void*) const (this=0x37de3b0, v=0x37de3b0)
    at /h/vcpkg-2023.12.12/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/lib/gprpp/thd_posix.cc:140
#13 0x0000000001238115 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::{lambda(void*)#1}::__invoke(void*) (v=0x37de3b0)
    at /h/vcpkg-2023.12.12/buildtrees/grpc/src/2948941d75-78cfc6f1b1.clean/src/core/lib/gprpp/thd_posix.cc:110
#14 0x00007f750f14f609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#15 0x00007f750ee6f353 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by coryan** [comment]
```
(gdb) info threads
  Id   Target Id                           Frame 
  1    Thread 0x7f750d31d700 (LWP 3150405) 0x0000000000f5a340 in std::_Rb_tree<grpc_core::ConnectivityStateWatcherInterface*, std::pair<grpc_core::ConnectivityStateWatcherInterface* const, std::unique_ptr<grpc_core::ConnectivityStateWatcherInterface, grpc_core::OrphanableDelete> >, std::_Select1st<std::pair<grpc_core::ConnectivityStateWatcherInterface* const, std::unique_ptr<grpc_core::ConnectivityStateWatcherInterface, grpc_core::OrphanableDelete> > >, std::less<grpc_core::ConnectivityStateWatcherInterface*>, std::allocator<std::pair<grpc_core::ConnectivityStateWatcherInterface* const, std::unique_ptr<grpc_core::ConnectivityStateWatcherInterface, grpc_core::OrphanableDelete> > > >::equal_range (this=0x152be69, __k=@0x7f750d31c870: 0x7f74fc04f990) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_tree.h:2002
  2    Thread 0x7f750642f700 (LWP 3148222) syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
  3    Thread 0x7f750ed4ecc0 (LWP 3109778) __pthread_clockjoin_ex (threadid=140140718778112, thread_return=0x0, clockid=<optimized out>, abstime=<optimized out>, block=<optimized out>) at pthread_join_common.c:145
  4    Thread 0x7f750dc2e700 (LWP 3148227) 0x00007f750ee6f68e in epoll_wait (epfd=9, events=0x37bde70, maxevents=100, timeout=51) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
  5    Thread 0x7f750ec30700 (LWP 3148223) syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
  6    Thread 0x7f750e42f700 (LWP 3148225) syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
* 7    Thread 0x7f750caf7700 (LWP 3159380) syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
```

**Comment by dbolduc** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/ca774926-a3fb-4138-abbb-31ee52020daf;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/ee9d78a0229653a59fdfc4b4ca954c4f36d96598/ubuntu-focal-cmake-oldest-deps/log-ca774926-a3fb-4138-abbb-31ee52020daf.txt

**Comment by coryan** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/f7e1cfe5-a891-4ea6-af48-e9fee38ee915;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/198ab5d3602c02a9450770486b6b1183526dbbc1/ubuntu-focal-cmake-oldest-deps/log-f7e1cfe5-a891-4ea6-af48-e9fee38ee915.txt

**Comment by coryan** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/9e014b5e-0d0a-4687-baa6-0bcd54107c2b;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/50758d245d7a88ae7e94d4232dda956131007471/ubuntu-focal-cmake-oldest-deps/log-9e014b5e-0d0a-4687-baa6-0bcd54107c2b.txt
