### ISSUE TITLE
[Flake]: Bigtable emulator crash during test.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2274]
The bigtable emulator crashed here:

https://source.cloud.google.com/results/invocations/4d0e30f1-a5e9-4a74-b6a7-13c97e55b510/targets/cloud-cpp%2Fgithub%2Fdocker%2Fclang-tidy/log

the relevant log lines are below.  I think we should upgrade to the latest and greatest google-cloud-sdk just on general principles. The line numbers do not match the source in:

https://github.com/googleapis/google-cloud-go/blob/master/bigtable/bttest/inmem.go

```
[ RUN      ]  table_admin_snippets drop-rows-by-prefix running
[    ERROR ]  table_admin_snippets drop-rows-by-prefix
================ [begin run_example.lGKnUA] ================
./table_admin_snippets drop-rows-by-prefix project-1553058091 in-1553058092 sample-table-for-admin-5715
Standard C++ exception raised: DropRowByPrefix(name=projects/project-1553058091/instances/in-1553058092/tables/sample-table-for-admin-5715) Socket closed
================ [end run_example.lGKnUA] ================
================ [begin emulator.log] ================
Cloud Bigtable emulator running on 127.0.0.1:46379
panic: runtime error: index out of range
goroutine 64 [running]:
github.com/google/btree.(*node).iterate(0xc000ff62c0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x100, 0xc00008dd18, 0x101)
	/usr/local/google/home/garyelliott/go/src/github.com/google/btree/btree.go:524 +0x88c
github.com/google/btree.(*node).iterate(0xc000ff6300, 0x1, 0x0, 0x0, 0x0, 0x0, 0xc000d90000, 0xc00008dd18, 0xc00067cb60)
	/usr/local/google/home/garyelliott/go/src/github.com/google/btree/btree.go:512 +0x5dd
github.com/google/btree.(*BTree).Ascend(0xc0011d4760, 0xc00008dd18)
	/usr/local/google/home/garyelliott/go/src/github.com/google/btree/btree.go:777 +0x5b
cloud.google.com/go/bigtable/bttest.(*table).gc(0xc000d906c0)
	/usr/local/google/home/garyelliott/go/src/cloud.google.com/go/bigtable/bttest/inmem.go:1188 +0x1e2
cloud.google.com/go/bigtable/bttest.(*server).gcloop(0xc0000ae400, 0xc000238840)
	/usr/local/google/home/garyelliott/go/src/cloud.google.com/go/bigtable/bttest/inmem.go:1097 +0x127
created by cloud.google.com/go/bigtable/bttest.(*server).needGC
	/usr/local/google/home/garyelliott/go/src/cloud.google.com/go/bigtable/bttest/inmem.go:1069 +0xa2
================ [end emulator.log] ================
```

**Comment by coryan** [comment]
Marking this blocked until we have more information.

**Comment by coryan** [comment]
Something like this happened again:

https://source.cloud.google.com/results/invocations/8c3451b2-30f3-43d2-81ed-3323769f1a74/targets/cloud-cpp%2Fgithub%2Fdocker%2Fshared/log

We are missing some logs to be able to troubleshoot.

**Comment by coryan** [comment]
Have not seen this in months. Closing.
