### ISSUE TITLE
Storage testbench broken due to Werkzeug

### ISSUE THREAD

**Issue by dopiera** [googleapis/google-cloud-cpp#3378]
Storage testbench fails to start in integration tests. The reason seems to be non-existent
`werkzeug.wsgi.DispatcherMiddleware`. I haven't figured out why.

This is the log:
```
[2020-02-09 23:49:31 +0000] [2999] [INFO] Starting gunicorn 19.10.0
[2020-02-09 23:49:31 +0000] [2999] [INFO] Listening at: http://0.0.0.0:33451 (2999)
[2020-02-09 23:49:31 +0000] [2999] [INFO] Using worker: gevent
[2020-02-09 23:49:31 +0000] [3006] [INFO] Booting worker with pid: 3006
[2020-02-09 23:49:32 +0000] [3006] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/arbiter.py", line 586, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 203, in init_process
    super(GeventWorker, self).init_process()
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/usr/lib64/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/v/google/cloud/storage/testbench/testbench.py", line 833, in <module>
    application = wsgi.DispatcherMiddleware(
AttributeError: 'module' object has no attribute 'DispatcherMiddleware'
[2020-02-09 23:49:32 +0000] [3006] [INFO] Worker exiting (pid: 3006)
[2020-02-09 23:49:32 +0000] [2999] [INFO] Shutting down: Master
[2020-02-09 23:49:32 +0000] [2999] [INFO] Reason: Worker failed to boot.
```

**Comment by coryan** [comment]
Fixed in #3377
