### ISSUE TITLE
[flake] Max retries reached sending request via Trawler State: URL_TIMEOUT

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp#4760]
Seen once on 2020-07- [artifacts - need to download build.log](https://source.cloud.google.com/results/invocations/2a18a2d3-8886-4a8d-90c4-4abc757a176c/targets/cloud-devrel%2Fclient-libraries%2Fcpp%2Fgoogle-cloud-cpp%2Fwindows%2Fbazel/artifacts)

```
[23:26:11] Build #506 enqueued, logging initialized.

[23:37:15][ERROR] Build being stopped due to fatal error, please see stack trace below. If you feel this is an issue with Kokoro please open a bug at http://go/kokoro-file-bug

java.io.IOException: Max retries reached sending request via Trawler: Url: "https://api.github.com/repos/googleapis/google-cloud-cpp/commits/ed8295611e042274038f29b0e93bc3960115637a"
Params {
  RequestorID: "kokoro-github"
  UserAgentsToObey: "Googlebot"
  HTTPOptions {
    Headers {
      key: "Authorization"
      value: "Basic MjM4YTg2NGUxOTc1MjgyMDE0YmFmZjM2MjFlZThhNGEyN2M2Y2JmZTp4LW9hdXRoLWJhc2lj"
    }
  }
  StreamParams {
    StreamInterval: 1045876
    MaxStreamInterval: 2097152
  }
}

	at com.google.devtools.kokoro.common.TrawlerClient.fetchRequestStreamingWithRetry(TrawlerClient.java:108)
	at com.google.devtools.kokoro.github.GithubHelper.getCommit(GithubHelper.java:243)
	at com.google.devtools.kokoro.github.GithubHelper.getCommit(GithubHelper.java:232)
	at com.google.devtools.kokoro.jenkins.plugin.github.GithubCheckoutStrategy.resolveScmRevisionState(GithubCheckoutStrategy.java:190)
	at com.google.devtools.kokoro.jenkins.plugin.github.GithubCheckoutStrategy.doCheckout(GithubCheckoutStrategy.java:249)
	at com.google.devtools.kokoro.jenkins.shared.ScmCheckoutStrategy.checkout(ScmCheckoutStrategy.java:44)
	at com.google.devtools.kokoro.jenkins.shared.KokoroScm.checkoutOrResolve(KokoroScm.java:91)
	at com.google.devtools.kokoro.jenkins.shared.KokoroScm.checkout(KokoroScm.java:61)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:109)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:83)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:73)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:221)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.devtools.kokoro.common.RetriableException: Failed to send request to Trawler: Url: "https://api.github.com/repos/googleapis/google-cloud-cpp/commits/ed8295611e042274038f29b0e93bc3960115637a"
Params {
  RequestorID: "kokoro-github"
  UserAgentsToObey: "Googlebot"
  HTTPOptions {
    Headers {
      key: "Authorization"
      value: "Basic MjM4YTg2NGUxOTc1MjgyMDE0YmFmZjM2MjFlZThhNGEyN2M2Y2JmZTp4LW9hdXRoLWJhc2lj"
    }
  }
  StreamParams {
    StreamInterval: 1045876
    MaxStreamInterval: 2097152
  }
}
, status: State: URL_TIMEOUT
Reason: 8
, will retry

[...]

[23:37:56] Sending email notification
	TO List: [cloud-cxx-team+kokoro@google.com]
	CC List: []
[23:37:57] Updating SpongeV2 invocation.
[23:38:02] Updating ResultStore invocation.
```

**Comment by coryan** [comment]
Should we file a bug with Kokoro then?  The URL works for me (today), maybe Kokoro needs a better retry strategy or something.

**Comment by mr-salty** [comment]
IDK if it's a Kokoro bug or just a transient problem - looks like it retried for ~10 minutes and couldn't contact github. Can we configure kokoro to re-run failed builds?

**Comment by coryan** [comment]
AFAIK, we can only retry PRs, Kokoro does not retry full builds.

**Comment by coryan** [comment]
No repeats in 90d, closing.
