### ISSUE TITLE
[Flake] Pub/Sub sample crash

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#4921]
This did not fail on the PR, but failed on the full build, possibly a flake, but if so,
frequent enough to require a quick fix:

https://source.cloud.google.com/results/invocations/b48ee7ab-34f6-455b-a315-de028c515ea5

```
FAIL: //google/cloud/pubsub/samples:samples (see /h/.cache/bazel/_bazel_kbuilder/a7ecd8237744645c5d189c197108d6d2/execroot/com_github_googleapis_google_cloud_cpp/bazel-out/k8-fastbuild/testlogs/google/cloud/pubsub/samples/samples/test.log)
INFO: From Testing //google/cloud/pubsub/samples:samples:
==================== Test output for //google/cloud/pubsub/samples:samples:

... ... ...
... ...
...

Running SubscribeErrorListener() sample
    #0 0x557ace in std::__1::shared_ptr<google::cloud::v1::internal::future_shared_state<void> >::~shared_ptr() /usr/bin/../include/c++/v1/memory:4206:9
    #1 0x55bff1 in std::__1::shared_ptr<google::cloud::v1::internal::future_shared_state<void> >::reset() /usr/bin/../include/c++/v1/memory:4342:5
    #2 0x5003dd in google::cloud::v1::internal::continuation<google::cloud::v1::internal::then_helper<(anonymous namespace)::Subscribe(google::cloud::pubsub::v1::Subscriber, google::cloud::pubsub::v1::Subscription const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)::$_2::operator()(google::cloud::pubsub::v1::Subscriber, google::cloud::pubsub::v1::Subscription const&) const::'lambda'(google::cloud::v1::future<void>), void, 0>::future_t google::cloud::v1::future<void>::then_impl<(anonymous namespace)::Subscribe(google::cloud::pubsub::v1::Subscriber, google::cloud::pubsub::v1::Subscription const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)::$_2::operator()(google::cloud::pubsub::v1::Subscriber, google::cloud::pubsub::v1::Subscription const&) const::'lambda'(google::cloud::v1::future<void>)>((anonymous namespace)::Subscribe(google::cloud::pubsub::v1::Subscriber, google::cloud::pubsub::v1::Subscription const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)::$_2::operator()(google::cloud::pubsub::v1::Subscriber, google::cloud::pubsub::v1::Subscription const&) const::'lambda'(google::cloud::v1::future<void>)&&, std::__1::integral_constant<bool, false>)::adapter, void>::execute() /proc/self/cwd/./google/cloud/internal/future_impl.h:694:12
    #3 0x55c39e in google::cloud::v1::internal::future_shared_state_base::notify_now(std::__1::unique_lock<std::__1::mutex>) /proc/self/cwd/./google/cloud/internal/future_impl.h:241:22
    #4 0x55cd2d in google::cloud::v1::internal::future_shared_state<void>::set_value() /proc/self/cwd/./google/cloud/internal/future_impl.h:507:5
    #5 0x577b1a in google::cloud::v1::promise<void>::set_value() /proc/self/cwd/./google/cloud/future_void.h:186:20
    #6 0x4fefcb in (anonymous namespace)::Subscribe(google::cloud::pubsub::v1::Subscriber, google::cloud::pubsub::v1::Subscription const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)::$_2::operator()(google::cloud::pubsub::v1::Subscriber, google::cloud::pubsub::v1::Subscription const&) const::'lambda'(google::cloud::pubsub::v1::Message const&, google::cloud::pubsub::v1::AckHandler)::operator()(google::cloud::pubsub::v1::Message const&, google::cloud::pubsub::v1::AckHandler) const /proc/self/cwd/google/cloud/pubsub/samples/samples.cc:528:51
    #7 0x4fedbc in decltype(std::__1::forward<(anonymous namespace)::Subscribe(google::cloud::pubsub::v1::Subscriber, google::cloud::pubsub::v1::Subscription const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)::$_2::operator()(google::cloud::pubsub::v1::Subscriber, google::cloud::pubsub::v1::Subscription const&) const::'lambda'(google::cloud::pubsub::v1::Message const&, google::cloud::pubsub::v1::AckHandler)&>(fp)(std::__1::forward<google::cloud::pubsub::v1::Message>(fp0), std::__1::forward<google::cloud::pubsub::v1::AckHandler>(fp0))) std::__1::__invoke<(anonymous namespace)::Subscribe(google::cloud::pubsub::v1::Subscriber, google::cloud::pubsub::v1::Subscription const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)::$_2::operator()(google::cloud::pubsub::v1::Subscriber, google::cloud::pubsub::v1::Subscription const&) const::'lambda'(google::cloud::pubsub::v1::Message const&, google::cloud::pubsub::v1::AckHandler)&, google::cloud::pubsub::v1::Message, google::cloud::pubsub::v1::AckHandler>((anonymous namespace)::Subscribe(google::cloud::pubsub::v1::Subscriber, google::cloud::pubsub::v1::Subscription const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)::$_2::operator()(google::cloud::pubsub::v1::Subscriber, google::cloud::pubsub::v1::Subscription const&) const::'lambda'(google::cloud::pubsub::v1::Message const&, google::cloud::pubsub::v1::AckHandler)&, google::cloud::pubsub::v1::Message&&, google::cloud::pubsub::v1::AckHandler&&) /usr/bin/../include/c++/v1/type_traits:3539:1
    #8 0x4fec20 in void std::__1::__invoke_void_return_wrapper<void>::__call<(anonymous namespace)::Subscribe(google::cloud::pubsub::v1::Subscriber, google::cloud::pubsub::v1::Subscription const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)::$_2::operator()(google::cloud::pubsub::v1::Subscriber, google::cloud::pubsub::v1::Subscription const&) const::'lambda'(google::cloud::pubsub::v1::Message const&, google::cloud::pubsub::v1::AckHandler)&, google::cloud::pubsub::v1::Message, google::cloud::pubsub::v1::AckHandler>((anonymous namespace)::Subscribe(google::cloud::pubsub::v1::Subscriber, google::cloud::pubsub::v1::Subscription const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)::$_2::operator()(google::cloud::pubsub::v1::Subscriber, google::cloud::pubsub::v1::Subscription const&) const::'lambda'(google::cloud::pubsub::v1::Message const&, google::cloud::pubsub::v1::AckHandler)&, google::cloud::pubsub::v1::Message&&, google::cloud::pubsub::v1::AckHandler&&) /usr/bin/../include/c++/v1/__functional_base:348:9
    #9 0x4feb10 in std::__1::__function::__alloc_func<(anonymous namespace)::Subscribe(google::cloud::pubsub::v1::Subscriber, google::cloud::pubsub::v1::Subscription const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)::$_2::operator()(google::cloud::pubsub::v1::Subscriber, google::cloud::pubsub::v1::Subscription const&) const::'lambda'(google::cloud::pubsub::v1::Message const&, google::cloud::pubsub::v1::AckHandler), std::__1::allocator<(anonymous namespace)::Subscribe(google::cloud::pubsub::v1::Subscriber, google::cloud::pubsub::v1::Subscription const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)::$_2::operator()(google::cloud::pubsub::v1::Subscriber, google::cloud::pubsub::v1::Subscription const&) const::'lambda'(google::cloud::pubsub::v1::Message const&, google::cloud::pubsub::v1::AckHandler)>, void (google::cloud::pubsub::v1::Message, google::cloud::pubsub::v1::AckHandler)>::operator()(google::cloud::pubsub::v1::Message&&, google::cloud::pubsub::v1::AckHandler&&) /usr/bin/../include/c++/v1/functional:1540:16
    #10 0x4fcbaa in std::__1::__function::__func<(anonymous namespace)::Subscribe(google::cloud::pubsub::v1::Subscriber, google::cloud::pubsub::v1::Subscription const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)::$_2::operator()(google::cloud::pubsub::v1::Subscriber, google::cloud::pubsub::v1::Subscription const&) const::'lambda'(google::cloud::pubsub::v1::Message const&, google::cloud::pubsub::v1::AckHandler), std::__1::allocator<(anonymous namespace)::Subscribe(google::cloud::pubsub::v1::Subscriber, google::cloud::pubsub::v1::Subscription const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)::$_2::operator()(google::cloud::pubsub::v1::Subscriber, google::cloud::pubsub::v1::Subscription const&) const::'lambda'(google::cloud::pubsub::v1::Message const&, google::cloud::pubsub::v1::AckHandler)>, void (google::cloud::pubsub::v1::Message, google::cloud::pubsub::v1::AckHandler)>::operator()(google::cloud::pubsub::v1::Message&&, google::cloud::pubsub::v1::AckHandler&&) /usr/bin/../include/c++/v1/functional:1714:12
    #11 0x7ff7675f34b4 in std::__1::__function::__value_func<void (google::cloud::pubsub::v1::Message, google::cloud::pubsub::v1::AckHandler)>::operator()(google::cloud::pubsub::v1::Message&&, google::cloud::pubsub::v1::AckHandler&&) const /usr/bin/../include/c++/v1/functional:1867:16
    #12 0x7ff7675f32a7 in std::__1::function<void (google::cloud::pubsub::v1::Message, google::cloud::pubsub::v1::AckHandler)>::operator()(google::cloud::pubsub::v1::Message, google::cloud::pubsub::v1::AckHandler) const /usr/bin/../include/c++/v1/functional:2473:12
    #13 0x7ff7675cd7fe in google::cloud::pubsub_internal::v1::SubscriptionSession::HandleQueue(std::__1::unique_lock<std::__1::mutex>)::MoveCapture::operator()() /proc/self/cwd/google/cloud/pubsub/internal/subscription_session.cc:240:7
    #14 0x7ff7675cd60c in void google::cloud::v1::CompletionQueue::RunAsync<google::cloud::pubsub_internal::v1::SubscriptionSession::HandleQueue(std::__1::unique_lock<std::__1::mutex>)::MoveCapture, 0>(google::cloud::pubsub_internal::v1::SubscriptionSession::HandleQueue(std::__1::unique_lock<std::__1::mutex>)::MoveCapture&&)::Wrapper::exec() /proc/self/cwd/./google/cloud/completion_queue.h:223:30
    #15 0x7ff767427228 in google::cloud::v1::(anonymous namespace)::AsyncFunction::Notify(bool) /proc/self/cwd/google/cloud/completion_queue.cc:100:11
    #16 0x7ff76744c01a in google::cloud::v1::internal::CompletionQueueImpl::Run() /proc/self/cwd/google/cloud/internal/completion_queue_impl.cc:44:13
    #17 0x7ff76741f384 in google::cloud::v1::CompletionQueue::Run() /proc/self/cwd/google/cloud/completion_queue.cc:115:38
    #18 0x7ff76744a6c8 in google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads::AutomaticallyCreatedBackgroundThreads()::$_0::operator()(google::cloud::v1::CompletionQueue) const /proc/self/cwd/google/cloud/internal/background_threads_impl.cc:23:43
    #19 0x7ff76744a659 in decltype(std::__1::forward<google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads::AutomaticallyCreatedBackgroundThreads()::$_0>(fp)(std::__1::forward<google::cloud::v1::CompletionQueue>(fp0))) std::__1::__invoke<google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads::AutomaticallyCreatedBackgroundThreads()::$_0, google::cloud::v1::CompletionQueue>(google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads::AutomaticallyCreatedBackgroundThreads()::$_0&&, google::cloud::v1::CompletionQueue&&) /usr/bin/../include/c++/v1/type_traits:3539:1
    #20 0x7ff76744a51d in void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads::AutomaticallyCreatedBackgroundThreads()::$_0, google::cloud::v1::CompletionQueue, 2ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads::AutomaticallyCreatedBackgroundThreads()::$_0, google::cloud::v1::CompletionQueue>&, std::__1::__tuple_indices<2ul>) /usr/bin/../include/c++/v1/thread:273:5
    #21 0x7ff767449fc0 in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads::AutomaticallyCreatedBackgroundThreads()::$_0, google::cloud::v1::CompletionQueue> >(void*) /usr/bin/../include/c++/v1/thread:284:5
    #22 0x7ff763f4e431 in start_thread (/lib64/libpthread.so.0+0x9431)
    #23 0x7ff763e299d2 in clone (/lib64/libc.so.6+0x1019d2)

```

**Comment by coryan** [comment]
Not just with msan it seems:

https://source.cloud.google.com/results/invocations/001dcbcf-6029-41a3-bb0b-a101254c6910

**Comment by coryan** [comment]
Another.

https://source.cloud.google.com/results/invocations/56726526-bddf-479f-9c7f-74025e509dd4
