### ISSUE TITLE
[Flake] pubsub throughput test fails with asan

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#5379]
https://source.cloud.google.com/results/invocations/017e607a-d90c-460b-97a5-69e0350e2bc4/details

```
Timestamp,Op,Iteration,Count,Bytes,ElapsedUs,MBs
2020-10-30T15:38:21.956589555Z,Pub,0,268,548864,1000140,0.55
2020-10-30T15:38:21.972388095Z,Sub,0,468,958464,1000095,0.96
# status= [OK], count=468
# Publisher: error_count=0, hwm_count=0
=================================================================
==5533==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7fe9129fb8b0 at pc 0x000000562b89 bp 0x7fe9111f81c0 sp 0x7fe9111f81b8
WRITE of size 8 at 0x7fe9129fb8b0 thread T7
    #0 0x562b88 in std::__atomic_base<long>::operator++() /usr/bin/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/atomic_base.h:326:16
    #1 0x53502b in (anonymous namespace)::PublisherTask((anonymous namespace)::Config const&)::$_4::operator()(int) const::'lambda'(google::cloud::v1::future<google::cloud::v1::StatusOr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >)::operator()(google::cloud::v1::future<google::cloud::v1::StatusOr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >) const /proc/self/cwd/google/cloud/pubsub/benchmarks/throughput.cc:290:13
    #2 0x534e37 in google::cloud::v1::internal::then_helper<(anonymous namespace)::PublisherTask((anonymous namespace)::Config const&)::$_4::operator()(int) const::'lambda'(google::cloud::v1::future<google::cloud::v1::StatusOr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >), google::cloud::v1::StatusOr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, 0>::future_t google::cloud::v1::future<google::cloud::v1::StatusOr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::then_impl<(anonymous namespace)::PublisherTask((anonymous namespace)::Config const&)::$_4::operator()(int) const::'lambda'(google::cloud::v1::future<google::cloud::v1::StatusOr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >)>((anonymous namespace)::PublisherTask((anonymous namespace)::Config const&)::$_4::operator()(int) const::'lambda'(google::cloud::v1::future<google::cloud::v1::StatusOr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >)&&, std::integral_constant<bool, false>)::adapter::operator()(std::shared_ptr<google::cloud::v1::internal::future_shared_state<google::cloud::v1::StatusOr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >) /proc/self/cwd/./google/cloud/internal/future_then_impl.h:71:14
    #3 0x534bf2 in void google::cloud::v1::internal::continuation_execute_delegate<google::cloud::v1::internal::then_helper<(anonymous namespace)::PublisherTask((anonymous namespace)::Config const&)::$_4::operator()(int) const::'lambda'(google::cloud::v1::future<google::cloud::v1::StatusOr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >), google::cloud::v1::StatusOr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, 0>::future_t google::cloud::v1::future<google::cloud::v1::StatusOr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::then_impl<(anonymous namespace)::PublisherTask((anonymous namespace)::Config const&)::$_4::operator()(int) const::'lambda'(google::cloud::v1::future<google::cloud::v1::StatusOr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >)>((anonymous namespace)::PublisherTask((anonymous namespace)::Config const&)::$_4::operator()(int) const::'lambda'(google::cloud::v1::future<google::cloud::v1::StatusOr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >)&&, std::integral_constant<bool, false>)::adapter, google::cloud::v1::StatusOr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >((anonymous namespace)::PublisherTask((anonymous namespace)::Config const&)::$_4::operator()(int) const::'lambda'(google::cloud::v1::future<google::cloud::v1::StatusOr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >)&, std::shared_ptr<google::cloud::v1::internal::future_shared_state<google::cloud::v1::internal::then_helper<(anonymous namespace)::PublisherTask((anonymous namespace)::Config const&)::$_4::operator()(int) const::'lambda'(google::cloud::v1::future<google::cloud::v1::StatusOr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >), google::cloud::v1::StatusOr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, 0>::future_t google::cloud::v1::future<google::cloud::v1::StatusOr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::then_impl<(anonymous namespace)::PublisherTask((anonymous namespace)::Config const&)::$_4::operator()(int) const::'lambda'(google::cloud::v1::future<google::cloud::v1::StatusOr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >)>((anonymous namespace)::PublisherTask((anonymous namespace)::Config const&)::$_4::operator()(int) const::'lambda'(google::cloud::v1::future<google::cloud::v1::StatusOr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >)&&, std::integral_constant<bool, false>)::adapter> >, google::cloud::v1::internal::future_shared_state<void>&, std::integral_constant<bool, false>) /proc/self/cwd/./google/cloud/internal/future_impl.h:634:5
    #4 0x53498e in google::cloud::v1::internal::continuation<google::cloud::v1::internal::then_helper<(anonymous namespace)::PublisherTask((anonymous namespace)::Config const&)::$_4::operator()(int) const::'lambda'(google::cloud::v1::future<google::cloud::v1::StatusOr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >), google::cloud::v1::StatusOr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, 0>::future_t google::cloud::v1::future<google::cloud::v1::StatusOr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::then_impl<(anonymous namespace)::PublisherTask((anonymous namespace)::Config const&)::$_4::operator()(int) const::'lambda'(google::cloud::v1::future<google::cloud::v1::StatusOr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >)>((anonymous namespace)::PublisherTask((anonymous namespace)::Config const&)::$_4::operator()(int) const::'lambda'(google::cloud::v1::future<google::cloud::v1::StatusOr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >)&&, std::integral_constant<bool, false>)::adapter, google::cloud::v1::StatusOr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::execute() /proc/self/cwd/./google/cloud/internal/future_impl.h:692:5
    #5 0x561f1b in google::cloud::v1::internal::future_shared_state_base::notify_now(std::unique_lock<std::mutex>) /proc/self/cwd/./google/cloud/internal/future_impl.h:241:22
    #6 0x7fe91ac33aa4 in google::cloud::v1::internal::future_shared_state<google::cloud::v1::StatusOr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::set_value(google::cloud::v1::StatusOr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >) /proc/self/cwd/./google/cloud/internal/future_impl.h:403:5
    #7 0x7fe91ac337f7 in google::cloud::v1::promise<google::cloud::v1::StatusOr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::set_value(google::cloud::v1::StatusOr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >) /proc/self/cwd/./google/cloud/future_generic.h:198:26
    #8 0x7fe91ac3fb37 in google::cloud::pubsub_internal::v1::Batch::operator()(google::cloud::v1::future<google::cloud::v1::StatusOr<google::pubsub::v1::PublishResponse> >)::SetValue::operator()() /proc/self/cwd/google/cloud/pubsub/internal/batching_publisher_connection.cc:48:34
    #9 0x7fe91ac3fa5c in void google::cloud::v1::CompletionQueue::RunAsync<google::cloud::pubsub_internal::v1::Batch::operator()(google::cloud::v1::future<google::cloud::v1::StatusOr<google::pubsub::v1::PublishResponse> >)::SetValue, 0>(google::cloud::pubsub_internal::v1::Batch::operator()(google::cloud::v1::future<google::cloud::v1::StatusOr<google::pubsub::v1::PublishResponse> >)::SetValue&&)::Wrapper::exec() /proc/self/cwd/./google/cloud/completion_queue.h:226:30
    #10 0x7fe91aa072a3 in google::cloud::v1::internal::(anonymous namespace)::AsyncFunction::Notify(bool) /proc/self/cwd/google/cloud/internal/default_completion_queue_impl.cc:106:8
    #11 0x7fe91aa031c7 in google::cloud::v1::internal::DefaultCompletionQueueImpl::Run() /proc/self/cwd/google/cloud/internal/default_completion_queue_impl.cc:132:13
    #12 0x7fe91aa02984 in google::cloud::v1::CompletionQueue::Run() /proc/self/cwd/./google/cloud/completion_queue.h:52:23
    #13 0x7fe91aa01538 in google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads::AutomaticallyCreatedBackgroundThreads(unsigned long, google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads::NormalizeTag)::$_0::operator()() const::'lambda'(google::cloud::v1::CompletionQueue)::operator()(google::cloud::v1::CompletionQueue) const /proc/self/cwd/google/cloud/internal/background_threads_impl.cc:34:52
    #14 0x7fe91aa01484 in void std::__invoke_impl<void, google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads::AutomaticallyCreatedBackgroundThreads(unsigned long, google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads::NormalizeTag)::$_0::operator()() const::'lambda'(google::cloud::v1::CompletionQueue), google::cloud::v1::CompletionQueue>(std::__invoke_other, google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads::AutomaticallyCreatedBackgroundThreads(unsigned long, google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads::NormalizeTag)::$_0::operator()() const::'lambda'(google::cloud::v1::CompletionQueue)&&, google::cloud::v1::CompletionQueue&&) /usr/bin/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60:14
    #15 0x7fe91aa013a0 in std::__invoke_result<google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads::AutomaticallyCreatedBackgroundThreads(unsigned long, google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads::NormalizeTag)::$_0::operator()() const::'lambda'(google::cloud::v1::CompletionQueue), google::cloud::v1::CompletionQueue>::type std::__invoke<google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads::AutomaticallyCreatedBackgroundThreads(unsigned long, google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads::NormalizeTag)::$_0::operator()() const::'lambda'(google::cloud::v1::CompletionQueue), google::cloud::v1::CompletionQueue>(google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads::AutomaticallyCreatedBackgroundThreads(unsigned long, google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads::NormalizeTag)::$_0::operator()() const::'lambda'(google::cloud::v1::CompletionQueue)&&, google::cloud::v1::CompletionQueue&&) /usr/bin/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:95:14
    #16 0x7fe91aa01380 in void std::thread::_Invoker<std::tuple<google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads::AutomaticallyCreatedBackgroundThreads(unsigned long, google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads::NormalizeTag)::$_0::operator()() const::'lambda'(google::cloud::v1::CompletionQueue), google::cloud::v1::CompletionQueue> >::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) /usr/bin/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/thread:264:13
    #17 0x7fe91aa01368 in std::thread::_Invoker<std::tuple<google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads::AutomaticallyCreatedBackgroundThreads(unsigned long, google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads::NormalizeTag)::$_0::operator()() const::'lambda'(google::cloud::v1::CompletionQueue), google::cloud::v1::CompletionQueue> >::operator()() /usr/bin/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/thread:271:11
    #18 0x7fe91aa0131c in std::thread::_State_impl<std::thread::_Invoker<std::tuple<google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads::AutomaticallyCreatedBackgroundThreads(unsigned long, google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads::NormalizeTag)::$_0::operator()() const::'lambda'(google::cloud::v1::CompletionQueue), google::cloud::v1::CompletionQueue> > >::_M_run() /usr/bin/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/thread:215:13
    #19 0x7fe91b0c86a3  (/lib64/libstdc++.so.6+0xd66a3)
    #20 0x7fe9180143f8 in start_thread (/lib64/libpthread.so.0+0x93f8)
    #21 0x7fe917f13b02 in clone (/lib64/libc.so.6+0x101b02)

Address 0x7fe9129fb8b0 is located in stack of thread T4 at offset 10128 in frame
    #0 0x52f46f in (anonymous namespace)::PublisherTask((anonymous namespace)::Config const&) /proc/self/cwd/google/cloud/pubsub/benchmarks/throughput.cc:227

  This frame has 41 object(s):
    [32, 64) 'publisher_options' (line 228)
    [96, 128) 'ref.tmp' (line 229)
    [160, 384) 'connection_options' (line 232)
    [448, 672) 'ref.tmp2' (line 233)
    [736, 768) 'agg.tmp'
    [800, 801) 'ref.tmp3' (line 233)
    [816, 832) 'publisher' (line 239)
    [848, 864) 'agg.tmp16'
    [880, 944) 'agg.tmp17'
    [976, 1008) 'agg.tmp18'
    [1040, 1072) 'agg.tmp21'
    [1104, 1136) 'agg.tmp26'
    [1168, 1392) 'agg.tmp28'
    [1456, 1464) 'agg.tmp30'
    [1488, 1496) 'agg.tmp31'
    [1520, 1552) 'agg.tmp34'
    [1584, 4088) 'gen' (line 242)
    [4224, 9224) 'ref.tmp45' (line 242)
    [9488, 9520) 'data' (line 243)
    [9552, 9584) 'ref.tmp56' (line 243)
    [9616, 9617) 'ref.tmp57' (line 243)
    [9632, 9672) 'pending_mu' (line 246)
    [9712, 9760) 'pending_cv' (line 247)
    [9792, 9800) 'pending' (line 248)
    [9824, 9832) 'hwm_count' (line 249)
    [9856, 9864) 'lwm' (line 250)
    [9888, 9896) 'hwm' (line 251)
    [9920, 9968) 'pending_wait' (line 252)
    [10000, 10032) 'pending_done' (line 259)
    [10064, 10088) 'pending_nothing' (line 263)
    [10128, 10136) 'send_count' (line 268) <== Memory access at offset 10128 is inside this variable
    [10160, 10168) 'error_count' (line 269)
    [10192, 10193) 'shutdown' (line 270)
    [10208, 10264) 'worker' (line 271)
    [10304, 10328) 'workers' (line 295)
    [10368, 10372) 'task_id' (line 296)
    [10384, 10584) 'usage' (line 304)
    [10656, 10688) 'ref.tmp95' (line 310)
    [10720, 10721) 'ref.tmp96' (line 310)
    [10736, 10744) '__begin1' (line 313)
    [10768, 10776) '__end1' (line 313)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
Thread T4 created by T0 here:
    #0 0x46fe52 in pthread_create (/h/.cache/bazel/_bazel_kbuilder/a7ecd8237744645c5d189c197108d6d2/execroot/com_github_googleapis_google_cloud_cpp/bazel-out/k8-fastbuild/bin/google/cloud/pubsub/benchmarks/throughput+0x46fe52)
    #1 0x7fe91b0c8948 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/lib64/libstdc++.so.6+0xd6948)
    #2 0x5433d8 in void __gnu_cxx::new_allocator<std::thread>::construct<std::thread, void (&)((anonymous namespace)::Config const&), (anonymous namespace)::Config&>(std::thread*, void (&)((anonymous namespace)::Config const&), (anonymous namespace)::Config&) /usr/bin/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/ext/new_allocator.h:150:23
    #3 0x542f81 in void std::allocator_traits<std::allocator<std::thread> >::construct<std::thread, void (&)((anonymous namespace)::Config const&), (anonymous namespace)::Config&>(std::allocator<std::thread>&, std::thread*, void (&)((anonymous namespace)::Config const&), (anonymous namespace)::Config&) /usr/bin/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/alloc_traits.h:512:8
    #4 0x543137 in void std::vector<std::thread, std::allocator<std::thread> >::_M_realloc_insert<void (&)((anonymous namespace)::Config const&), (anonymous namespace)::Config&>(__gnu_cxx::__normal_iterator<std::thread*, std::vector<std::thread, std::allocator<std::thread> > >, void (&)((anonymous namespace)::Config const&), (anonymous namespace)::Config&) /usr/bin/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/vector.tcc:449:4
    #5 0x52f430 in void std::vector<std::thread, std::allocator<std::thread> >::emplace_back<void (&)((anonymous namespace)::Config const&), (anonymous namespace)::Config&>(void (&)((anonymous namespace)::Config const&), (anonymous namespace)::Config&) /usr/bin/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/vector.tcc:121:4
    #6 0x52e39d in main /proc/self/cwd/google/cloud/pubsub/benchmarks/throughput.cc:180:11
    #7 0x7fe917e3a1a1 in __libc_start_main (/lib64/libc.so.6+0x281a1)

SUMMARY: AddressSanitizer: stack-use-after-scope /usr/bin/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/atomic_base.h:326:16 in std::__atomic_base<long>::operator++()
Shadow bytes around the buggy address:
  0x0ffda25376c0: f2 f2 f2 f2 f2 f2 f8 f8 f8 f8 f2 f2 f2 f2 f8 f8
  0x0ffda25376d0: f8 f8 f2 f2 f2 f2 f8 f2 f8 f8 f8 f8 f8 f2 f2 f2
  0x0ffda25376e0: f2 f2 f8 f8 f8 f8 f8 f8 f2 f2 f2 f2 f8 f2 f2 f2
  0x0ffda25376f0: f8 f2 f2 f2 f8 f2 f2 f2 f8 f2 f2 f2 f8 f8 f8 f8
  0x0ffda2537700: f8 f8 f2 f2 f2 f2 f8 f8 f8 f8 f2 f2 f2 f2 f8 f8
=>0x0ffda2537710: f8 f2 f2 f2 f2 f2[f8]f2 f2 f2 f8 f2 f2 f2 f8 f2
  0x0ffda2537720: f8 f8 f8 f8 f8 f8 f8 f2 f2 f2 f2 f2 f8 f8 f8 f2
  0x0ffda2537730: f2 f2 f2 f2 f8 f2 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8
  0x0ffda2537740: f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f2
  0x0ffda2537750: f2 f2 f2 f2 f2 f2 f2 f2 f8 f8 f8 f8 f2 f2 f2 f2
  0x0ffda2537760: f8 f2 f8 f2 f2 f2 f8 f3 f3 f3 f3 f3 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
Thread T7 created by T4 here:
    #0 0x46fe52 in pthread_create (/h/.cache/bazel/_bazel_kbuilder/a7ecd8237744645c5d189c197108d6d2/execroot/com_github_googleapis_google_cloud_cpp/bazel-out/k8-fastbuild/bin/google/cloud/pubsub/benchmarks/throughput+0x46fe52)
    #1 0x7fe91b0c8948 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/lib64/libstdc++.so.6+0xd6948)
    #2 0x7fe91aa01024 in google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads::AutomaticallyCreatedBackgroundThreads(unsigned long, google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads::NormalizeTag)::$_0::operator()() const /proc/self/cwd/google/cloud/internal/background_threads_impl.cc:34:12
    #3 0x7fe91aa00cb2 in __gnu_cxx::__normal_iterator<std::thread*, std::vector<std::thread, std::allocator<std::thread> > > std::generate_n<__gnu_cxx::__normal_iterator<std::thread*, std::vector<std::thread, std::allocator<std::thread> > >, unsigned long, google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads::AutomaticallyCreatedBackgroundThreads(unsigned long, google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads::NormalizeTag)::$_0>(__gnu_cxx::__normal_iterator<std::thread*, std::vector<std::thread, std::allocator<std::thread> > >, unsigned long, google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads::AutomaticallyCreatedBackgroundThreads(unsigned long, google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads::NormalizeTag)::$_0) /usr/bin/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/stl_algo.h:4483:13
    #4 0x7fe91aa00a85 in google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads::AutomaticallyCreatedBackgroundThreads(unsigned long, google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads::NormalizeTag) /proc/self/cwd/google/cloud/internal/background_threads_impl.cc:33:3
    #5 0x7fe91aa00b88 in google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads::AutomaticallyCreatedBackgroundThreads(unsigned long) /proc/self/cwd/google/cloud/internal/background_threads_impl.cc:28:7
    #6 0x7fe91a9fb51f in absl::lts_2020_02_25::memory_internal::MakeUniqueResult<google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads>::scalar absl::lts_2020_02_25::make_unique<google::cloud::v1::internal::AutomaticallyCreatedBackgroundThreads, unsigned long&>(unsigned long&) /proc/self/cwd/external/com_google_absl/absl/memory/memory.h:170:33
    #7 0x7fe91a9faf28 in google::cloud::v1::internal::DefaultBackgroundThreads(unsigned long) /proc/self/cwd/google/cloud/connection_options.cc:43:10
    #8 0x7fe91acefa60 in google::cloud::v1::ConnectionOptions<google::cloud::pubsub::v1::ConnectionOptionsTraits>::background_threads_factory() const::'lambda'()::operator()() const /proc/self/cwd/./google/cloud/connection_options.h:234:25
    #9 0x7fe91acefa1b in google::cloud::pubsub::v1::ConnectionOptionsTraits std::__invoke_impl<std::unique_ptr<google::cloud::v1::BackgroundThreads, std::default_delete<google::cloud::v1::BackgroundThreads> >, google::cloud::v1::ConnectionOptions<google::cloud::pubsub::v1::ConnectionOptionsTraits>::background_threads_factory() const::'lambda'()&>(std::__invoke_other, google::cloud::v1::ConnectionOptions<google::cloud::pubsub::v1::ConnectionOptionsTraits>::background_threads_factory() const::'lambda'()&) /usr/bin/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60:14
    #10 0x7fe91acef9cb in std::enable_if<__and_<std::__not_<std::is_void<google::cloud::pubsub::v1::ConnectionOptionsTraits> >, std::is_convertible<std::__invoke_result<google::cloud::v1::ConnectionOptions<google::cloud::pubsub::v1::ConnectionOptionsTraits>::background_threads_factory() const::'lambda'()&>::type, google::cloud::pubsub::v1::ConnectionOptionsTraits> >::value, google::cloud::pubsub::v1::ConnectionOptionsTraits>::type std::__invoke_r<std::unique_ptr<google::cloud::v1::BackgroundThreads, std::default_delete<google::cloud::v1::BackgroundThreads> >, google::cloud::v1::ConnectionOptions<google::cloud::pubsub::v1::ConnectionOptionsTraits>::background_threads_factory() const::'lambda'()&>(google::cloud::v1::ConnectionOptions<google::cloud::pubsub::v1::ConnectionOptionsTraits>::background_threads_factory() const::'lambda'()&) /usr/bin/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:141:14
    #11 0x7fe91acef8bb in std::_Function_handler<std::unique_ptr<google::cloud::v1::BackgroundThreads, std::default_delete<google::cloud::v1::BackgroundThreads> > (), google::cloud::v1::ConnectionOptions<google::cloud::pubsub::v1::ConnectionOptionsTraits>::background_threads_factory() const::'lambda'()>::_M_invoke(std::_Any_data const&) /usr/bin/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:291:9
    #12 0x7fe91ace8525 in std::function<std::unique_ptr<google::cloud::v1::BackgroundThreads, std::default_delete<google::cloud::v1::BackgroundThreads> > ()>::operator()() const /usr/bin/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:622:14
    #13 0x7fe91ace53da in google::cloud::pubsub_internal::v1::MakePublisherConnection(google::cloud::pubsub::v1::Topic, google::cloud::pubsub::v1::PublisherOptions, google::cloud::v1::ConnectionOptions<google::cloud::pubsub::v1::ConnectionOptionsTraits>, std::shared_ptr<google::cloud::pubsub_internal::v1::PublisherStub>, std::unique_ptr<google::cloud::v1::internal::TraitBasedRetryPolicy<google::cloud::pubsub_internal::v1::RetryTraits> const, std::default_delete<google::cloud::v1::internal::TraitBasedRetryPolicy<google::cloud::pubsub_internal::v1::RetryTraits> const> >, std::unique_ptr<google::cloud::v1::internal::BackoffPolicy const, std::default_delete<google::cloud::v1::internal::BackoffPolicy const> >) /proc/self/cwd/google/cloud/pubsub/publisher_connection.cc:109:21
    #14 0x7fe91ace4e60 in google::cloud::pubsub::v1::MakePublisherConnection(google::cloud::pubsub::v1::Topic, google::cloud::pubsub::v1::PublisherOptions, google::cloud::v1::ConnectionOptions<google::cloud::pubsub::v1::ConnectionOptionsTraits>, std::unique_ptr<google::cloud::v1::internal::TraitBasedRetryPolicy<google::cloud::pubsub_internal::v1::RetryTraits> const, std::default_delete<google::cloud::v1::internal::TraitBasedRetryPolicy<google::cloud::pubsub_internal::v1::RetryTraits> const> >, std::unique_ptr<google::cloud::v1::internal::BackoffPolicy const, std::default_delete<google::cloud::v1::internal::BackoffPolicy const> >) /proc/self/cwd/google/cloud/pubsub/publisher_connection.cc:73:10
    #15 0x52fa4a in (anonymous namespace)::PublisherTask((anonymous namespace)::Config const&) /proc/self/cwd/google/cloud/pubsub/benchmarks/throughput.cc:239:31
    #16 0x54399b in void std::__invoke_impl<void, void (*)((anonymous namespace)::Config const&), (anonymous namespace)::Config>(std::__invoke_other, void (*&&)((anonymous namespace)::Config const&), (anonymous namespace)::Config&&) /usr/bin/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60:14
    #17 0x543958 in std::__invoke_result<void (*)((anonymous namespace)::Config const&), (anonymous namespace)::Config>::type std::__invoke<void (*)((anonymous namespace)::Config const&), (anonymous namespace)::Config>(void (*&&)((anonymous namespace)::Config const&), (anonymous namespace)::Config&&) /usr/bin/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:95:14
    #18 0x543944 in void std::thread::_Invoker<std::tuple<void (*)((anonymous namespace)::Config const&), (anonymous namespace)::Config> >::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) /usr/bin/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/thread:264:13
    #19 0x543918 in std::thread::_Invoker<std::tuple<void (*)((anonymous namespace)::Config const&), (anonymous namespace)::Config> >::operator()() /usr/bin/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/thread:271:11
    #20 0x5436bc in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)((anonymous namespace)::Config const&), (anonymous namespace)::Config> > >::_M_run() /usr/bin/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/thread:215:13
    #21 0x7fe91b0c86a3  (/lib64/libstdc++.so.6+0xd66a3)

==5533==ABORTING
================================================================================
```

**Comment by coryan** [comment]
I was able to repro in a container. With this change it fails reliably:

```patch
diff --git a/google/cloud/pubsub/benchmarks/throughput.cc b/google/cloud/pubsub/benchmarks/throughput.cc
index 9b3c8a770..094639c89 100644
--- a/google/cloud/pubsub/benchmarks/throughput.cc
+++ b/google/cloud/pubsub/benchmarks/throughput.cc
@@ -287,6 +287,7 @@ void PublisherTask(Config const& config) {
                        .Build())
           .then([&](future<StatusOr<std::string>> f) {
             pending_done();
+            std::this_thread::sleep_for(std::chrono::microseconds(100));
             ++send_count;
             if (!f.get()) ++error_count;
           });
```

Obviously we are signaling the thread that the work is "done" and then doing some additional work. Not a good idea.
