### ISSUE TITLE
[flake] kokoro failed with "Failed to parse JSON"

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp#5509]
I don't see anything actionable here since the error message (`Caused by: org.json.JSONException: A JSONObject text must begin with '{' at character 0 of `) doesn't give us much to go on; filing this for tracking purposes in case it happens again.

Note that no email was generated for this, it was only visible in testgrid with a '?!' status.

```
[10:09:37] Build #823 enqueued, logging initialized.
[10:09:37] Test Fusion Url: http://fusion/runanalysis/info/prod%3Acloud-cpp%2Fgithub%2Fgoogle-cloud-cpp%2Fmaster%2Finstall%2Fubuntu-focal/prod%3Acloud-cpp%2Fgithub%2Fgoogle-cloud-cpp%2Fmaster%2Finstall%2Fubuntu-focal/KOKORO/6ff5cdb1-8a7c-4924-89b9-fc6643346ad6/0/prod%3Acloud-cpp%2Fgithub%2Fgoogle-cloud-cpp%2Fmaster%2Finstall%2Fubuntu-focal/Targets 
[10:12:10] Build LEASED by executor 531378599 (sigma: http://sigma.corp.google.com/global/-/#search_jobs?query=kokoro+exec+531378599 )
[10:12:21] Check log in ResultStore UI: https://source.cloud.google.com/results/invocations/6ff5cdb1-8a7c-4924-89b9-fc6643346ad6
[10:12:21] Paired Machine Hostname: kokoro-gcp-ubuntu-prod-531378599
[10:12:21] Deleting workspace contents
[10:12:21] Workspace did not exist
[10:12:21] Finished deleting workspace contents
[10:12:22] Resolving Github Scm Revision State
[10:14:43][ERROR] Build being stopped due to fatal error, please see stack trace below. If you feel this is an issue with Kokoro please open a bug at http://go/kokoro-file-bug

java.io.IOException: Failed to parse JSON: 
	at com.google.devtools.kokoro.github.GithubHelper.getJsonObject(GithubHelper.java:956)
	at com.google.devtools.kokoro.github.GithubHelper.getCommit(GithubHelper.java:250)
	at com.google.devtools.kokoro.github.GithubHelper.getCommit(GithubHelper.java:232)
	at com.google.devtools.kokoro.jenkins.plugin.github.GithubCheckoutStrategy.resolveScmRevisionState(GithubCheckoutStrategy.java:190)
	at com.google.devtools.kokoro.jenkins.plugin.github.GithubCheckoutStrategy.doCheckout(GithubCheckoutStrategy.java:249)
	at com.google.devtools.kokoro.jenkins.shared.ScmCheckoutStrategy.checkout(ScmCheckoutStrategy.java:44)
	at com.google.devtools.kokoro.jenkins.shared.KokoroScm.checkoutOrResolve(KokoroScm.java:91)
	at com.google.devtools.kokoro.jenkins.shared.KokoroScm.checkout(KokoroScm.java:61)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:109)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:83)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:73)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:221)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.json.JSONException: A JSONObject text must begin with '{' at character 0 of 
	at org.json.JSONTokener.syntaxError(JSONTokener.java:451)
	at org.json.JSONObject.<init>(JSONObject.java:179)
	at org.json.JSONObject.<init>(JSONObject.java:326)
	at com.google.devtools.kokoro.github.GithubHelper.getJsonObject(GithubHelper.java:954)
	... 18 more
```

**Comment by coryan** [comment]
No repeats in 90d, closing.
