### ISSUE TITLE
[Flake] macOS: bazel failed to fetch all external deps

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#6156]
https://source.cloud.google.com/results/invocations/0e7dc7ea-55ea-4453-afb9-b0499bb87732/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp%2Fmaster%2Fmacos%2Fbazel/log

**2021-03-29T23:51:04Z**

Example:
```
2021-03-29T23:53:04Z: Fetch bazel dependencies [2/3].
Loading: 0 packages loaded
INFO: Repository local_config_cc instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule cc_autoconf defined at:
  /Volumes/BuildData/tmpfs/tmp/bazel/external/bazel_tools/tools/cpp/cc_configure.bzl:143:30: in <toplevel>
Loading: 0 packages loaded
ERROR: An error occurred during the fetch of repository 'local_config_cc':
   Traceback (most recent call last):
	File "/Volumes/BuildData/tmpfs/tmp/bazel/external/bazel_tools/tools/cpp/cc_configure.bzl", line 123, column 32, in cc_autoconf_impl
		configure_osx_toolchain(repository_ctx, overriden_tools)
	File "/Volumes/BuildData/tmpfs/tmp/bazel/external/bazel_tools/tools/cpp/osx_cc_configure.bzl", line 138, column 17, in configure_osx_toolchain
		fail("wrapped_clang failed to generate. Please file an issue at " +
Error in fail: wrapped_clang failed to generate. Please file an issue at https://github.com/bazelbuild/bazel/issues with the following:
return code 256, stderr: Timed out, stdout:
ERROR: /Volumes/BuildData/tmpfs/tmp/bazel/external/bazel_tools/tools/cpp/BUILD:93:6: no such package '@local_config_cc//': wrapped_clang failed to generate. Please file an issue at https://github.com/bazelbuild/bazel/issues with the following:
return code 256, stderr: Timed out, stdout:  and referenced by '@bazel_tools//tools/cpp:toolchain'
ERROR: /Volumes/BuildData/tmpfs/tmp/bazel/external/bazel_tools/tools/cpp/BUILD:93:6: no such package '@local_config_cc//': wrapped_clang failed to generate. Please file an issue at https://github.com/bazelbuild/bazel/issues with the following:
return code 256, stderr: Timed out, stdout:  and referenced by '@bazel_tools//tools/cpp:toolchain'
ERROR: Evaluation of query "deps((... union @local_config_platform//... union @local_config_cc_toolchains//... union @local_config_sh//... union @go_sdk//... union @remotejdk11_macos//:jdk))" failed: errors were encountered while computing transitive closure
Loading: 0 packages loaded
Loading: 0 packages loaded
2021-03-29T23:54:27Z: bazel fetch failed with 2
```

**Comment by coryan** [comment]
This seems similar (maybe a dup) of #5836
